In [6]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [7]:
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [8]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [9]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [10]:
Y_train

array([0, 3, 3, ..., 3, 4, 7])

In [11]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5 
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def deriv_ReLU(Z):
    return Z>0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T 
    return one_hot_Y

def back_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 -  alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 -  alpha * dW2
    b2 = b2 - alpha * db2 
    return W1, b1, W2, b2
    

In [12]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("iteration:", i)
            predictions = get_predictions(A2)
            print("accuracy:", get_accuracy(predictions, Y))
    return W1, b1, W2, b2         
            
            
        
        
    
    

In [13]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

iteration: 0
[2 5 8 ... 8 3 3] [0 3 3 ... 3 4 7]
accuracy: 0.1001219512195122
iteration: 10
[0 3 8 ... 3 0 0] [0 3 3 ... 3 4 7]
accuracy: 0.17748780487804877
iteration: 20
[0 3 3 ... 3 0 0] [0 3 3 ... 3 4 7]
accuracy: 0.2617560975609756
iteration: 30
[0 3 3 ... 3 0 0] [0 3 3 ... 3 4 7]
accuracy: 0.3318536585365854
iteration: 40
[0 3 3 ... 3 0 9] [0 3 3 ... 3 4 7]
accuracy: 0.38609756097560977
iteration: 50
[0 3 3 ... 3 0 9] [0 3 3 ... 3 4 7]
accuracy: 0.434609756097561
iteration: 60
[0 3 3 ... 3 0 9] [0 3 3 ... 3 4 7]
accuracy: 0.5134390243902439
iteration: 70
[0 3 3 ... 3 0 9] [0 3 3 ... 3 4 7]
accuracy: 0.5729512195121951
iteration: 80
[0 3 3 ... 3 0 7] [0 3 3 ... 3 4 7]
accuracy: 0.6127560975609756
iteration: 90
[0 3 3 ... 3 0 7] [0 3 3 ... 3 4 7]
accuracy: 0.6412926829268293
iteration: 100
[0 3 3 ... 3 0 7] [0 3 3 ... 3 4 7]
accuracy: 0.664219512195122
iteration: 110
[0 3 3 ... 3 0 7] [0 3 3 ... 3 4 7]
accuracy: 0.6813902439024391
iteration: 120
[0 3 3 ... 3 4 7] [0 3 3 ... 3 4 7]


In [14]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("prediction:", prediction)
    print("label:, label")
    
    current_image = current_image.reshape((28, 28) * 255)
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()
    
    

In [15]:
test_prediction(0, W1, b1, W2, b2)
test_prediction(1, W1, b1, W2, b2)
test_prediction(2, W1, b1, W2, b2)
test_prediction(3, W1, b1, W2, b2)

prediction: [0]
label:, label


ValueError: maximum supported dimension for an ndarray is 32, found 510